import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AppSidebar from "@/components/Sidebar";

const inter = Almarai({
  subsets: ["arabic"], weight: ["400", "700", '800']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >

      <body className={inter.className}> <AppSidebar /><Header />

        {children}</body>
    </html >
  );
}
